# Generated by Django 5.1.4 on 2024-12-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrueba', '0003_alter_product_name_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
